on:
  push

name: Test Edit Issue

jobs:
  test-edit-issue:
    name: Edit Issue
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Login
      uses: atlassian/gajira-login@master
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

    - name: Create new issue
      id: create
      uses: atlassian/gajira-create@master
      with:
        project: GA
        issuetype: Build
        summary: |
          Build completed for ${{ github.repository }}
        description: |
          Compare branch|${{ github.event.compare }} # https://developer.github.com/v3/activity/events/types/#webhook-payload-example-31

    - name: Edit issue
      uses: ./
      with:
        issue: ${{ steps.create.outputs.issue }}
        summary: |
          ${{ github.event.issue.title }}
        description: |
          ${{ github.event.issue.body }}

    - name: Log edited issue
      run: echo "Issue ${{ steps.edit.outputs.issue }} was edited"
